ci:
  autoupdate_schedule: "quarterly"
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.8
  hooks:
    - id: ruff-format
    - id: ruff-check
      args: [--fix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.6.0
  hooks:
    - id: pyproject-fmt
