[build-system]
requires = [
  "setuptools >= 40.9.0",
  "versioneer[toml]==0.26",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "openff-nagl-models"
description = "OpenFF NAGL Models"
license = { file = "LICENSE" }
authors = [
    {name = "Lily Wang", email = "lily.wang@openforcefield.org"},
]
maintainers = [
    {name = "Lily Wang", email = "lily.wang@openforcefield.org"},
]
readme = "README.md"
requires-python = ">=3.9"
dynamic = ["version"]
dependencies = [
    "importlib_resources",
]

[project.optional-dependencies]
test = [
    "pytest>=6.0",
    "numpy",
]

[project.entry-points."openforcefield.nagl_model_directory"]
get_nagl_model_dirs_paths = "openff.nagl_models:get_nagl_model_dirs_paths"

[project.urls]
source = "https://github.com/openforcefield/openff-nagl-models"
# documentation = "https://openff-nagl-models.readthedocs.io"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "openff/nagl_models/tests",
]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "openff/nagl_models/_version.py"
versionfile_build = "openff/nagl_models/_version.py"
tag_prefix = "v"
parentdir_prefix = "openff-nagl-models-" 
